name: Test
on:
  push:
     branches:
      - main
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: get code
      uses: actions/checkout@v3
      - name: install deps
      run: npm install
      - name: run tests
      run: npm run test
